<?php

namespace StockBundle\Repository;

/**
 * LigneWishlistRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LigneWishlistRepository extends \Doctrine\ORM\EntityRepository
{
}
