<?php

namespace WorkshopBundle\Repository;

/**
 * ParticipantWorkRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantWorkRepository extends \Doctrine\ORM\EntityRepository
{
}
