<?php

namespace WorkshopBundle\Repository;

/**
 * PlanningWorkshopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanningWorkshopRepository extends \Doctrine\ORM\EntityRepository
{
}
