stock_homepage:
    path:     /
    defaults: { _controller: StockBundle:Default:index }

ajout_produit:
    path:     /ajout-produit
    defaults: { _controller: StockBundle:Produit:ajout }

affiche_produits:
    path:     /affiche-produits
    defaults: { _controller: StockBundle:Produit:affiche }

modif_produits:
    path:     /affiche-produits/modif/{id}
    defaults: { _controller: StockBundle:Produit:modifier }

supp_produits:
        path:     /affiche-produits/supp/{id}
        defaults: { _controller: StockBundle:Produit:supprimer }

recherche_produits:
        path:     /recherche-produits
        defaults: { _controller: StockBundle:Produit:recherche }

view_produit:
        path:    /view-produit/{id}
        defaults: { _controller: StockBundle:Produit:produit }

art_produits:
        path:     /art-produits
        defaults: { _controller: StockBundle:Produit:art }

habillement_produits:
        path:     /habillement-produits
        defaults: { _controller: StockBundle:Produit:habillement }

bijoux_produits:
        path:     /bijoux-produits
        defaults: { _controller: StockBundle:Produit:bijoux }

territoire_produits:
        path:     /terrtoire-produits
        defaults: { _controller: StockBundle:Produit:territoire }

maroquinerie_produits:
        path:     /maroquinerie-produits
        defaults: { _controller: StockBundle:Produit:maroquinerie }

decoration_produits:
        path:     /decoration-produits
        defaults: { _controller: StockBundle:Produit:decoration }

libsort_produits:
        path:     /libsort-produits
        defaults: { _controller: StockBundle:Produit:libsort }

prixasc_produits:
        path:     /prixasc-produits
        defaults: { _controller: StockBundle:Produit:prixasc }

prixdesc_produits:
        path:     /prixdesc-produits
        defaults: { _controller: StockBundle:Produit:prixdesc }

ajout_wishlist:
    path:     /ajout-wishlist/{id}
    defaults: { _controller: StockBundle:Wishlist:ajout }

affiche_wishlist:
    path:     /affiche-wishlist
    defaults: { _controller: StockBundle:Wishlist:affiche }

supprimer_wishlist:
    path:     /supprimer-wishlist/{id}
    defaults: { _controller: StockBundle:Wishlist:supprimer }

affiche_produitsWS:
    path:     /affiche-produitsWS
    defaults: { _controller: StockBundle:Produit:afficheWS }

ajout_produitWS:
    path:     /ajout-produitWS/{id}/{libelle}/{description}/{image}/{prix}/{quqntite}/{promotion}
    defaults: { _controller: StockBundle:Produit:ajoutWS }
afficher_Ligne_Wishlist_Json:
    path:     /afficherLWJson/{id}
    defaults: { _controller: StockBundle:Wishlist:afficheLWishlistJson }
ajout_Ligne_Wishlist_Json:
    path:     /ajouterLWJson/{id}/{idP}
    defaults: { _controller: StockBundle:Wishlist:ajoutLWishlistJson }
supprimer_Ligne_Wishlist_Json:
    path:     /supprimerLWJson/{id}
    defaults: { _controller: StockBundle:Wishlist:supprimerLWishist }