<?php

namespace EvenementBundle\Repository;

/**
 * ParticipantEventsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParticipantEventsRepository extends \Doctrine\ORM\EntityRepository
{
}
