SocialBundle\Entity\Post:
    type: entity
    table: null
    repositoryClass: SocialBundle\Repository\PostRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idUser:
            type: integer
        date:
            type: date
        texte:
            type: string
            length: 255
            nullable: true
        picLink:
            type: string
            length: 255
            nullable: true
            unique: true
        nbSignal:
            type: integer
            nullable: true
    lifecycleCallbacks: {  }
