social_homepage:
    path:     /
    defaults: { _controller: SocialBundle:Default:index }

social_ajout_profile:
    path:     /add
    defaults: { _controller: SocialBundle:Default:add }

social_modifier_profile:
    path:     /mod/{id}
    defaults: { _controller: SocialBundle:Default:modifier }

social_recherche_profile:
    path:     /rech
    defaults: { _controller: SocialBundle:Default:search }

social_check_profile:
    path:     /check/{id}
    defaults: { _controller: SocialBundle:Default:check }

social_delete_profile:
    path:     /del/{id}
    defaults: { _controller: SocialBundle:Default:delete }

social_delete_image:
    path:     /delim/{id}
    defaults: { _controller: SocialBundle:Default:delImage }

social_suivre_user:
    path:     /suiv/{id}
    defaults: { _controller: SocialBundle:Default:follow }

social_pasuivre_user:
    path:     /pasuiv/{id}
    defaults: { _controller: SocialBundle:Default:unfollow }

social_delete_post:
    path:     /delp/{id}
    defaults: { _controller: SocialBundle:Default:delPost }

social_modifier_post:
    path:     /modp/{id}
    defaults: { _controller: SocialBundle:Default:modPost }

social_delete_post_fromWelcome:
    path:     /delp/{id}
    defaults: { _controller: SocialBundle:Default:delPost }

social_modifier_post_fromWelcome:
    path:     /modp/{id}
    defaults: { _controller: SocialBundle:Default:modPost }

social_suivreAX_user:
    path:     /suivAX/{id}
    defaults: { _controller: SocialBundle:Default:followAX }

social_pasuivreAX_user:
    path:     /pasuivAX/{id}
    defaults: { _controller: SocialBundle:Default:unfollowAX }

social_postsAX_home:
    path:     /postsAX/{deb}/{fin}
    defaults: { _controller: SocialBundle:Default:postsAX }

social_postsWS:
    path:     /postsHomeWS/{userid}
    defaults: { _controller: SocialBundle:Default:postsHomeWS }

social_followWS:
    path:     /followSwitchWS/{idProfileFollower}/{idProfileFollowed}
    defaults: { _controller: SocialBundle:Default:followHomeSwitchWS }

social_deleteWS:
    path:     /delPostWS/{id}
    defaults: { _controller: SocialBundle:Default:deleteHomeWS }

social_addWS:
    path:     /addPostWS/{id}/{titre}/{texte}/{image}
    defaults: { _controller: SocialBundle:Default:addPostHomeWS }

social_modWS:
    path:     /modPostWS/{id}/{titre}/{texte}
    defaults: { _controller: SocialBundle:Default:modPostHomeWS }

social_uniqWS:
    path:     /uniqWS
    defaults: { _controller: SocialBundle:Default:getUniqWS }

social_findProfileWS:
    path:     /findProfWS/{id}
    defaults: { _controller: SocialBundle:Default:findProfileWS }