<?php

namespace SocialBundle\Repository;

/**
 * ProfileRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProfileRepository extends \Doctrine\ORM\EntityRepository
{
    public function findProfileUserId($id)
    {
        $query = $this->createQueryBuilder('p');
        $query -> andWhere("p.idUser = :idUser")
        ->setParameter('idUser',$id);
        return $query->getQuery()->getResult();
    }
}
