<?php

namespace LocalBundle\Repository;

/**
 * LocationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocationRepository extends \Doctrine\ORM\EntityRepository
{

    public function findDate($dateDeb,$dateFin)
    {
        $query= LocationRepository::createQueryBuilder('r')
            ->where('r.dateDebutLocation >= :dateDeb ')
            ->andWhere('r.dateDebutLocation <= :dateFin ')
            ->orWhere('r.dateFinLocation <= :dateFin')
            ->andWhere('r.dateFinLocation >= :dateDeb')
            ->setParameters(array('dateFin'=>$dateFin,'dateDeb'=>$dateDeb))
            ->getQuery();
        return $query->getResult();
    }


}
