commande_homepage:
    path:     /
    defaults: { _controller: CommandeBundle:Default:index }
commande_ajout:
    path:     /ajout/{id}
    defaults: { _controller: CommandeBundle:LigneDePanier:Ajout }
ligne_commande_aff:
    path:     /afflc
    defaults: { _controller: CommandeBundle:LigneDeCommande:AfficherLigneDeCommande }
panier_afficher:
    path:     /afficher
    defaults: { _controller: CommandeBundle:LigneDePanier:ModifierPanier }
ligne_commande_modifier:
    path:     /modifierlc/{id}
    defaults: { _controller: CommandeBundle:LigneDeCommande:ModifierLigneDeCommande }
ligne_commande_supprimer:
    path:     /supprimerlc/{id}
    defaults: { _controller: CommandeBundle:LigneDeCommande:SupprimerLigneDeCommande }
ligne_commande_ajouters:
    path:     /ajouterlcs
    defaults: { _controller: CommandeBundle:LigneDeCommande:PutInSession }
payement:
    path:     /ajoutlcs
    defaults: { _controller: CommandeBundle:LigneDeCommande:a }
ajout_ligne_commande:
    path:     /ajoutbd
    defaults: { _controller: CommandeBundle:LigneDeCommande:AjoutLigneDeCommande }