<?php

namespace Proxies\__CG__\LocalBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Local extends \LocalBundle\Entity\Local implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'id', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'idUser', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'superficie', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'prix', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'type', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'description', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'adresse', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'telephone', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'nbSignal', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'titre', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'image', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'located'];
        }

        return ['__isInitialized__', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'id', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'idUser', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'superficie', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'prix', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'type', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'description', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'adresse', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'telephone', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'nbSignal', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'titre', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'image', '' . "\0" . 'LocalBundle\\Entity\\Local' . "\0" . 'located'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Local $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUser($idUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUser', [$idUser]);

        return parent::setIdUser($idUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser', []);

        return parent::getIdUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setSuperficie($superficie)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSuperficie', [$superficie]);

        return parent::setSuperficie($superficie);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephone()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephone', []);

        return parent::getTelephone();
    }

    /**
     * {@inheritDoc}
     */
    public function getLocated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocated', []);

        return parent::getLocated();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocated($located)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocated', [$located]);

        return parent::setLocated($located);
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephone($telephone)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephone', [$telephone]);

        return parent::setTelephone($telephone);
    }

    /**
     * {@inheritDoc}
     */
    public function getSuperficie()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSuperficie', []);

        return parent::getSuperficie();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbSignal($nbSignal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbSignal', [$nbSignal]);

        return parent::setNbSignal($nbSignal);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbSignal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbSignal', []);

        return parent::getNbSignal();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getImage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImage', []);

        return parent::getImage();
    }

    /**
     * {@inheritDoc}
     */
    public function setImage($image)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImage', [$image]);

        return parent::setImage($image);
    }

}
