<?php

namespace Proxies\__CG__\EvenementBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Evenement extends \EvenementBundle\Entity\Evenement implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'id', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'nomEvenement', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'dateDebut', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'dateFin', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'heure', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'adresse', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'prix', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'description', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'nbPlace', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'nbSignal', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'type', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'idUser', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'photo', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'rating', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'nbrrating', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'nbruser'];
        }

        return ['__isInitialized__', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'id', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'nomEvenement', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'dateDebut', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'dateFin', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'heure', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'adresse', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'prix', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'description', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'nbPlace', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'nbSignal', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'type', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'idUser', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'photo', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'rating', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'nbrrating', '' . "\0" . 'EvenementBundle\\Entity\\Evenement' . "\0" . 'nbruser'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Evenement $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getHeure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeure', []);

        return parent::getHeure();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeure($heure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeure', [$heure]);

        return parent::setHeure($heure);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbrrating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbrrating', []);

        return parent::getNbrrating();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbrrating($nbrrating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbrrating', [$nbrrating]);

        return parent::setNbrrating($nbrrating);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbruser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbruser', []);

        return parent::getNbruser();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbruser($nbruser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbruser', [$nbruser]);

        return parent::setNbruser($nbruser);
    }

    /**
     * {@inheritDoc}
     */
    public function getRating()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRating', []);

        return parent::getRating();
    }

    /**
     * {@inheritDoc}
     */
    public function setRating($rating)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRating', [$rating]);

        return parent::setRating($rating);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoto()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoto', []);

        return parent::getPhoto();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoto($photo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoto', [$photo]);

        return parent::setPhoto($photo);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomEvenement($nomEvenement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomEvenement', [$nomEvenement]);

        return parent::setNomEvenement($nomEvenement);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomEvenement()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomEvenement', []);

        return parent::getNomEvenement();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebut($dateDebut)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebut', [$dateDebut]);

        return parent::setDateDebut($dateDebut);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebut()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebut', []);

        return parent::getDateDebut();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin($dateFin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', [$dateFin]);

        return parent::setDateFin($dateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', []);

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', [$adresse]);

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', []);

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbPlace($nbPlace)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbPlace', [$nbPlace]);

        return parent::setNbPlace($nbPlace);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbPlace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbPlace', []);

        return parent::getNbPlace();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbSignal($nbSignal)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbSignal', [$nbSignal]);

        return parent::setNbSignal($nbSignal);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbSignal()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbSignal', []);

        return parent::getNbSignal();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdUser($idUser)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUser', [$idUser]);

        return parent::setIdUser($idUser);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUser', []);

        return parent::getIdUser();
    }

}
